export const SET_THEME = "SET_THEME";

export const SET_LANGUAGE = "SET_LANGUAGE";

export const SET_OPEN_SNACKBAR = "SET_OPEN_SNACKBAR";
export const SET_CLOSE_SNACKBAR = "SET_CLOSE_SNACKBAR";

export const SET_CONFIRM_DIALOG_OPEN = "SET_CONFIRM_DIALOG_OPEN";
export const SET_CONFIRM_DIALOG_CANCEL = "SET_CONFIRM_DIALOG_CANCEL";
export const SET_CONFIRM_DIALOG_ACCEPT = "SET_CONFIRM_DIALOG_ACCEPT";
export const SET_CONFIRM_DIALOG_RESET_ACCEPT = "SET_CONFIRM_DIALOG_RESET_ACCEPT";

export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const RESET_USER_DATA = "RESET_USER_DATA";

export const SET_TECHNICS_PENDING = "SET_TECHNICS_PENDING";
export const SET_TECHNICS_DATA = "SET_TECHNICS_DATA";
export const SET_TECHNICS_ERROR = "SET_TECHNICS_ERROR";

export const SET_TAGS_PENDING = "SET_TAGS_PENDING";
export const SET_TAGS_DATA = "SET_TAGS_DATA";
export const SET_TAGS_ERROR = "SET_TAGS_ERROR";

export const SET_USER_POSTS_PENDING = "SET_USER_POSTS_PENDING";
export const SET_USER_POSTS_DATA = "SET_USER_POSTS_DATA";
export const SET_USER_POSTS_ERROR = "SET_USER_POSTS_ERROR";

export const SET_ADD_POST_PENDING = "SET_ADD_POST_PENDING";
export const SET_ADD_POST_DATA = "SET_ADD_POST_DATA";
export const SET_ADD_POST_ERROR = "SET_ADD_POST_ERROR";

export const SET_UPDATE_POST_PENDING = "SET_UPDATE_POST_PENDING";
export const SET_UPDATE_POST_DATA = "SET_UPDATE_POST_DATA";
export const SET_UPDATE_POST_ERROR = "SET_UPDATE_POST_ERROR";

export const SET_DELETE_POST_PENDING = "SET_DELETE_POST_PENDING";
export const SET_DELETE_POST_DATA = "SET_DELETE_POST_DATA";
export const SET_DELETE_POST_ERROR = "SET_DELETE_POST_ERROR";

export const SET_POST_COMMENTS_PENDING = "SET_POST_COMMENTS_PENDING";
export const SET_POST_COMMENTS_DATA = "SET_POST_COMMENTS_DATA";
export const SET_POST_COMMENTS_ERROR = "SET_POST_COMMENTS_ERROR";
export const CLEAR_POST_COMMENTS = "CLEAR_POST_COMMENTS";

export const SET_ADD_POST_COMMENT_PENDING = "SET_ADD_POST_COMMENT_PENDING";
export const SET_ADD_POST_COMMENT_DATA = "SET_ADD_POST_COMMENT_DATA";
export const SET_ADD_POST_COMMENT_ERROR = "SET_ADD_POST_COMMENT_ERROR";

export const SET_UPDATE_POST_COMMENT_PENDING = "SET_UPDATE_POST_COMMENT_PENDING";
export const SET_UPDATE_POST_COMMENT_DATA = "SET_UPDATE_POST_COMMENT_DATA";
export const SET_UPDATE_POST_COMMENT_ERROR = "SET_UPDATE_POST_COMMENT_ERROR";

export const SET_SEARCH_ICON_PENDING = "SET_SEARCH_ICON_PENDING";
export const SET_SEARCH_ICON_DATA = "SET_SEARCH_ICON_DATA";
export const SET_SEARCH_ICON_ERROR = "SET_SEARCH_ICON_ERROR";

export const SET_ADD_LOCATION_PENDING = "SET_ADD_LOCATION_PENDING";
export const SET_ADD_LOCATION_DATA = "SET_ADD_LOCATION_DATA";
export const SET_ADD_LOCATION_ERROR = "SET_ADD_LOCATION_ERROR";